### ISSUE TITLE
NameError: uninitialized constant DateTime

### ISSUE THREAD

**Issue by msxavi** [jobready/capistrano-server#4]
```
deploy@nep-infra-build01:~/neptune$ bundle exec cap staging deploy:last_deployed --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
[Deprecation Notice] `set :scm, :git` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git

** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env 
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
  INFO rbenv: rbenv_ruby is not set; ruby version will be defined by the remote hosts via rbenv
  INFO rbenv: rbenv_ruby is not set; ruby version will be defined by the remote hosts via rbenv
** Invoke rbenv:map_bins (first_time)
** Execute rbenv:map_bins
** Invoke deploy:last_deployed (first_time)
** Execute deploy:last_deployed
cap aborted!
NameError: uninitialized constant DateTime
/home/deploy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/capistrano-server-47d5f2584c93/lib/capistrano/tasks/deployment.rake:4:in `block (2 levels) in <top (required)>'
/home/deploy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/deploy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/deploy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/deploy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in
```

**Comment by msxavi** [comment]
Fixed under #5 and included in `1.0.1`
